// Code generated by "stringer -type=CompressType"; DO NOT EDIT.

package gelf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CompressGzip-0]
	_ = x[CompressZlib-1]
	_ = x[CompressNone-2]
}

const _CompressType_name = "CompressGzipCompressZlibCompressNone"

var _CompressType_index = [...]uint8{0, 12, 24, 36}

func (i CompressType) String() string {
	if i < 0 || i >= CompressType(len(_CompressType_index)-1) {
		return "CompressType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CompressType_name[_CompressType_index[i]:_CompressType_index[i+1]]
}
